const char* startup_scm="(clear)\n"
"(colour (vector 0 0.5 1 1))\n"
"(scale (vector 0.3 0.3 0.3))\n"
"(define cubes\n"
"  (map \n"
"   (lambda (p)\n"
"     (with-primitive p\n"
"       (apply-transform)\n"
"       (translate (vector -2.5 2 5))\n"
"       (rotate (vector 45 0 0))\n"
"       (translate \n"
"        (vector\n"
"         (* 2 (quotient (- p 1) 5))\n"
"         0\n"
"         (* 2 (modulo (- p 1) 5))))\n"
"       p))\n"
"   (build-list\n"
"    (lambda (n) \n"
"      (with-state\n"
"       (scale (vector 1 0.1 1))\n"
"       (build-cube)))\n"
"    25)))\n"
"\n"
";(every-frame\n"
"; (for-each \n"
";  (lambda (p)\n"
";    (grab p) ;(with-primitive \n"
"    ; p\n"
";     (rotate (vector (* p 0.02) 0 (* p 0.06))) (ungrab)\n"
";)\n"
";  cubes))\n"
"                    \n"
"\n";
